<a href="https://colab.research.google.com/github/DaniBntz/AluraStore/blob/main/TelecomX_LATAM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ðŸ“Œ ExtracciÃ³n

In [35]:
import pandas as pd

dt = pd.read_json('/content/TelecomX_Data.json')

In [36]:
dt.head()

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."

In [37]:
#primero voy a extraer la informaciÃ³n anidada en las columnas 'customer', 'phone', 'internet' y 'account'

customer = pd.json_normalize(dt['customer'])
phone = pd.json_normalize(dt['phone'])
internet = pd.json_normalize(dt['internet'])
account = pd.json_normalize(dt['account'])

In [38]:
#ahora voy a unir todo en un solo DF para poder verlo mejor.

datos = pd.concat([dt, customer, phone, internet, account], axis=1)

In [39]:
#ahora que ya tengo el DF con la informaciÃ³n completa, eliminarÃ© las columnas
#customer, phone, internet, account, puesto que sobran en esta tabla ya que la
#informaciÃ³n ha sido extraida.

datos.drop(['customer', 'phone', 'internet', 'account'], axis=1, inplace=True)
#compruebo
datos.sample()

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
2561,3571-RFHAR,Yes,Male,0,No,No,65,Yes,Yes,Fiber optic,...,Yes,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,109.15,6941.2

In [40]:
datos.sample(5)

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
3685,5076-YVXCM,No,Male,0,No,No,51,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,No,Bank transfer (automatic),83.40,4149.45
5179,7069-PURBI,,Female,0,Yes,No,14,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.40,292.4
5024,6870-ECSHE,No,Female,0,No,No,2,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,One year,No,Mailed check,20.45,34.8
5050,6900-RBKER,No,Male,0,No,No,52,Yes,Yes,Fiber optic,...,No,Yes,No,No,Yes,Two year,Yes,Credit card (automatic),89.45,4577.75
5144,7020-OZKXZ,No,Female,1,No,No,9,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,No,Credit card (automatic),75.50,637.4

In [41]:
datos['OnlineSecurity'].sample(20)

4873                    Yes
786                      No
2603    No internet service
2193                     No
1545                    Yes
3051                    Yes
6790                     No
2480    No internet service
6902    No internet service
473     No internet service
1446                    Yes
7057                     No
440                     Yes
6995                     No
1223                     No
768                      No
4748    No internet service
6143                     No
1680                     No
3821                     No
Name: OnlineSecurity, dtype: object

#ðŸ”§ TransformaciÃ³n

In [42]:
#verifico la informaciÃ³n de mi DF

datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7267 non-null   object
 1   Churn             7267 non-null   object
 2   gender            7267 non-null   object
 3   SeniorCitizen     7267 non-null   int64
 4   Partner           7267 non-null   object
 5   Dependents        7267 non-null   object
 6   tenure            7267 non-null   int64
 7   PhoneService      7267 non-null   object
 8   MultipleLines     7267 non-null   object
 9   InternetService   7267 non-null   object
 10  OnlineSecurity    7267 non-null   object
 11  OnlineBackup      7267 non-null   object
 12  DeviceProtection  7267 non-null   object
 13  TechSupport       7267 non-null   object
 14  StreamingTV       7267 non-null   object
 15  StreamingMovies   7267 non-null   object
 16  Contract          7267 non-null   object
 17  PaperlessBilling  7267 non-null   object
 18  PaymentMethod     7267 non-null   object
 19  Charges.Monthly   7267 non-null   float64
 20  Charges.Total     7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

In [43]:
datos['OnlineSecurity'].sample(5)

2180     No
6435     No
2806    Yes
1731     No
1777    Yes
Name: OnlineSecurity, dtype: object

In [44]:
#despues de revisar y analizar la informaciÃ³n, encuentro que la columna 'Charges.Total' es de tipo object
#deberÃ­a ser tipo float. voy a convertirla a tipo float64
#para esto primero necesito eliminar los caracteres que me impiden hacer la conversiÃ³n

datos['Charges.Total'] = datos['Charges.Total'].str.replace(',', '').replace('$', '').replace(' ', '')

In [45]:
# Ahora, manejo explÃ­citamente los strings vacÃ­os ('') resultantes de los reemplazos.
# Esto es crucial porque el paso anterior puede dejar strings vacÃ­os si la cadena original
# solo contenÃ­a los caracteres que se reemplazaron, o si ya estaba vacÃ­a.
# Reemplazo los strings vacÃ­os por None, que pandas manejarÃ¡ como NaN (Not a Number)
# en una columna numÃ©rica. None es un valor que astype('float64') puede manejar.
datos['Charges.Total'] = datos['Charges.Total'].replace('', None)

In [46]:
#ahora si voy a convertirla a tipo float64
datos['Charges.Total'] = datos['Charges.Total'].astype('float64')

In [47]:
#compruebo
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7267 non-null   object
 1   Churn             7267 non-null   object
 2   gender            7267 non-null   object
 3   SeniorCitizen     7267 non-null   int64
 4   Partner           7267 non-null   object
 5   Dependents        7267 non-null   object
 6   tenure            7267 non-null   int64
 7   PhoneService      7267 non-null   object
 8   MultipleLines     7267 non-null   object
 9   InternetService   7267 non-null   object
 10  OnlineSecurity    7267 non-null   object
 11  OnlineBackup      7267 non-null   object
 12  DeviceProtection  7267 non-null   object
 13  TechSupport       7267 non-null   object
 14  StreamingTV       7267 non-null   object
 15  StreamingMovies   7267 non-null   object
 16  Contract          7267 non-null   object
 17  PaperlessBilling  7267 non-null   object
 18  PaymentMethod     7267 non-null   object
 19  Charges.Monthly   7267 non-null   float64
 20  Charges.Total     7256 non-null   float64
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [48]:
# La columna 'SeniorCitizen' estÃ¡ en formato 0 (No) y 1 (Yes).
# Verifico el tipo de dato actual antes de la conversiÃ³n
print(datos['SeniorCitizen'].dtype)

int64

In [49]:
# Realizo la conversiÃ³n a tipo booleano
datos['SeniorCitizen'] = datos['SeniorCitizen'].astype(bool)

In [50]:
#compruebo
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7267 non-null   object
 1   Churn             7267 non-null   object
 2   gender            7267 non-null   object
 3   SeniorCitizen     7267 non-null   bool
 4   Partner           7267 non-null   object
 5   Dependents        7267 non-null   object
 6   tenure            7267 non-null   int64
 7   PhoneService      7267 non-null   object
 8   MultipleLines     7267 non-null   object
 9   InternetService   7267 non-null   object
 10  OnlineSecurity    7267 non-null   object
 11  OnlineBackup      7267 non-null   object
 12  DeviceProtection  7267 non-null   object
 13  TechSupport       7267 non-null   object
 14  StreamingTV       7267 non-null   object
 15  StreamingMovies   7267 non-null   object
 16  Contract          7267 non-null   object
 17  PaperlessBilling  7267 non-null   object
 18  PaymentMethod     7267 non-null   object
 19  Charges.Monthly   7267 non-null   float64
 20  Charges.Total     7256 non-null   float64
dtypes: bool(1), float64(2), int64(1), object(17)
memory usage: 1.1+ MB

In [51]:
datos.sample(5)

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
5586,7634-HLQJR,No,Female,False,Yes,Yes,47,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),20.05,1016.70
2156,3014-WJKSM,No,Male,False,Yes,No,29,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Credit card (automatic),75.30,2263.40
4323,5939-SXWHM,No,Male,False,Yes,Yes,48,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),26.30,1245.05
1250,1790-NESIO,No,Female,False,No,No,13,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Mailed check,20.40,261.30
1528,2193-SFWQW,No,Male,False,Yes,Yes,72,Yes,No,Fiber optic,...,Yes,Yes,Yes,Yes,Yes,Two year,No,Bank transfer (automatic),111.95,8033.10

In [52]:
# Identifico que hay mÃ¡s columnas de tipo object que deberÃ­an ser booleanas.
colum_bool = [
    'Partner',
    'Dependents',
    'PhoneService',
    'PaperlessBilling',
    'Churn'
]

In [53]:
# Creo un diccionario de mapeo para convertir 'Yes' a True y 'No' a False.
mapeo1 = {'Yes': True, 'No': False}

In [55]:
# Aplico el mapeo a las columnas seleccionadas
# Selecciono las columnas y luego uso .map() en ellas.
# Esto aplica la transformaciÃ³n a cada valor en las columnas especificadas.
for col in colum_bool:
    # Verifico si la columna existe en el DataFrame para evitar errores
    if col in datos.columns:
        # Utilizo .loc para asegurar que la asignaciÃ³n se haga correctamente en el DataFrame original
        datos.loc[:, col] = datos[col].map(mapeo1)
    else:
        print(f"La columna '{col}' no se encontrÃ³ en el DataFrame.")

In [56]:
datos[colum_bool].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Partner           0 non-null      object
 1   Dependents        0 non-null      object
 2   PhoneService      0 non-null      object
 3   PaperlessBilling  0 non-null      object
 4   Churn             0 non-null      object
dtypes: object(5)
memory usage: 284.0+ KB

In [57]:
datos.sample(6)

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
4057,5553-AOINX,NaN,Female,True,NaN,NaN,66,NaN,Yes,Fiber optic,...,Yes,Yes,No,Yes,Yes,One year,NaN,Electronic check,104.90,6891.45
4787,6557-BZXLQ,NaN,Male,True,NaN,NaN,16,NaN,No,Fiber optic,...,No,No,No,No,No,Month-to-month,NaN,Electronic check,69.65,1043.30
5011,6855-VLGOS,NaN,Male,False,NaN,NaN,72,NaN,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,NaN,Electronic check,20.55,1432.55
5263,7180-PISOG,NaN,Male,False,NaN,NaN,1,NaN,Yes,Fiber optic,...,No,No,No,No,No,Month-to-month,NaN,Electronic check,74.50,74.50
4649,6368-NWMCE,NaN,Female,False,NaN,NaN,38,NaN,Yes,DSL,...,Yes,No,Yes,No,Yes,Month-to-month,NaN,Credit card (automatic),68.15,2656.30
3621,4990-ALDGW,NaN,Male,False,NaN,NaN,57,NaN,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,NaN,Mailed check,20.75,1118.80

In [58]:
#ahora si puedo transformar esas columnas en tipo bool
datos[colum_bool] = datos[colum_bool].astype('bool')

In [59]:
#compruebo
datos[colum_bool].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Partner           7267 non-null   bool
 1   Dependents        7267 non-null   bool
 2   PhoneService      7267 non-null   bool
 3   PaperlessBilling  7267 non-null   bool
 4   Churn             7267 non-null   bool
dtypes: bool(5)
memory usage: 35.6 KB

In [60]:
datos.sample(10)

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
1896,2682-KEVRP,True,Female,True,True,True,22,True,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,One year,True,Mailed check,20.05,417.00
1829,2606-PKWJB,True,Male,False,True,True,40,True,No phone service,DSL,...,Yes,No,Yes,No,No,One year,True,Mailed check,40.25,1564.05
6277,8631-XVRZL,True,Male,False,True,True,9,True,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,One year,True,Mailed check,20.15,163.70
947,1335-MXCSE,True,Male,False,True,True,55,True,No,DSL,...,No,Yes,Yes,No,No,Two year,True,Credit card (automatic),55.25,3119.90
5370,7330-WZLNC,True,Female,False,True,True,5,True,Yes,Fiber optic,...,Yes,No,No,Yes,No,Month-to-month,True,Electronic check,90.80,455.50
4439,6082-OQFBA,True,Male,False,True,True,23,True,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,One year,True,Mailed check,19.65,436.90
1479,2122-YWVYA,True,Female,False,True,True,18,True,No,Fiber optic,...,No,No,No,No,No,Month-to-month,True,Electronic check,75.40,1380.40
3217,4488-PSYCG,True,Male,False,True,True,16,True,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,True,Bank transfer (automatic),20.25,327.45
6675,9174-FKWZE,True,Female,True,True,True,1,True,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,True,Electronic check,19.45,19.45
1950,2761-XECQW,True,Male,True,True,True,8,True,No phone service,DSL,...,Yes,Yes,No,No,Yes,Month-to-month,True,Mailed check,43.35,371.40

In [61]:
#ahora, hay otras columnas que tambiÃ©n deben ser transformadas a Booleano, pero
#dentro de algunas filas hay valores que impedirÃ­an la fÃ¡cil conversiÃ³n, es por eso
#que estas columnas quiero cambiar primero algunos valores antes de transformarlas

colum_bool2 = [
    'MultipleLines',
    'InternetService',
    'OnlineSecurity',
    'OnlineBackup',
    'DeviceProtection',
    'TechSupport',
    'StreamingTV',
    'StreamingMovies'
              ]

In [62]:
# Creo un diccionario de mapeo expandido para incluir el tercer valor.
mapeo2 = {
    'Yes': True,
    'No': False,
    'DSL': True,
    'Fiber optic': True,
    'No phone service': False,
    'No internet service': False # Incluyo este tambiÃ©n, es comÃºn en las columnas relacionadas con internet
}

In [64]:
# Aplico el mapeo expandido a las columnas seleccionadas
for col in colum_bool2:
    # Verifico si la columna existe y es de tipo object antes de intentar mapear
    if col in datos.columns and datos[col].dtype == 'object':
         # Utilizo .loc para asegurar la asignaciÃ³n correcta
         datos.loc[:, col] = datos[col].map(mapeo2)
    elif col in datos.columns:
         print(f"La columna '{col}' no es de tipo object. No se aplicÃ³ el mapeo.")
    else:
        print(f"La columna '{col}' no se encontrÃ³ en el DataFrame.")

In [65]:
#verifico
datos[colum_bool2].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   MultipleLines     7267 non-null   object
 1   InternetService   7267 non-null   object
 2   OnlineSecurity    7267 non-null   object
 3   OnlineBackup      7267 non-null   object
 4   DeviceProtection  7267 non-null   object
 5   TechSupport       7267 non-null   object
 6   StreamingTV       7267 non-null   object
 7   StreamingMovies   7267 non-null   object
dtypes: object(8)
memory usage: 454.3+ KB

In [66]:
#ahora si puedo hacer la transformaciÃ³n a bool
datos[colum_bool2] = datos[colum_bool2].astype('bool')

In [67]:
#compruebo nuevamente
datos[colum_bool2].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   MultipleLines     7267 non-null   bool
 1   InternetService   7267 non-null   bool
 2   OnlineSecurity    7267 non-null   bool
 3   OnlineBackup      7267 non-null   bool
 4   DeviceProtection  7267 non-null   bool
 5   TechSupport       7267 non-null   bool
 6   StreamingTV       7267 non-null   bool
 7   StreamingMovies   7267 non-null   bool
dtypes: bool(8)
memory usage: 56.9 KB

In [68]:
datos[colum_bool2].sample(5)

,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
2898,True,True,False,False,False,True,True,True
5176,False,False,False,False,False,False,False,False
5908,False,True,True,False,False,True,False,False
3709,False,True,False,False,False,False,False,False
2134,True,True,True,True,True,False,True,True

In [69]:
datos.sample(5)

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
3310,4615-PIVVU,True,Female,False,True,True,42,True,False,True,...,False,True,True,False,True,Two year,True,Credit card (automatic),66.50,2762.75
3534,4873-ILOLJ,True,Male,False,True,True,24,True,False,True,...,False,False,False,True,True,Month-to-month,True,Electronic check,90.35,2238.50
5296,7239-HZZCX,True,Male,False,True,True,1,True,False,False,...,False,False,False,False,False,Month-to-month,True,Mailed check,19.75,19.75
6313,8681-ICONS,True,Male,False,True,True,29,True,False,False,...,False,False,False,False,False,Month-to-month,True,Mailed check,20.65,654.85
3516,4846-WHAFZ,True,Female,True,True,True,37,True,True,True,...,False,False,False,False,False,Month-to-month,True,Electronic check,76.50,2868.15

In [70]:
#reviso los campos de contract
datos['Contract'].unique()

array(['One year', 'Month-to-month', 'Two year'], dtype=object)

In [71]:
#reviso los campos de PaymentMethod
datos['PaymentMethod'].unique()

array(['Mailed check', 'Electronic check', 'Credit card (automatic)',
       'Bank transfer (automatic)'], dtype=object)

In [72]:
#ahora sÃ­, todas las columnas tienen los datos corregidos con los que podemos hacer
#el anÃ¡lisis
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7267 non-null   object
 1   Churn             7267 non-null   bool
 2   gender            7267 non-null   object
 3   SeniorCitizen     7267 non-null   bool
 4   Partner           7267 non-null   bool
 5   Dependents        7267 non-null   bool
 6   tenure            7267 non-null   int64
 7   PhoneService      7267 non-null   bool
 8   MultipleLines     7267 non-null   bool
 9   InternetService   7267 non-null   bool
 10  OnlineSecurity    7267 non-null   bool
 11  OnlineBackup      7267 non-null   bool
 12  DeviceProtection  7267 non-null   bool
 13  TechSupport       7267 non-null   bool
 14  StreamingTV       7267 non-null   bool
 15  StreamingMovies   7267 non-null   bool
 16  Contract          7267 non-null   object
 17  PaperlessBilling  7267 non-null   bool
 18  PaymentMethod     7267 non-null   object
 19  Charges.Monthly   7267 non-null   float64
 20  Charges.Total     7256 non-null   float64
dtypes: bool(14), float64(2), int64(1), object(4)
memory usage: 496.9+ KB

In [73]:
#noto que las columnas: OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport
#StreamingTV y StreamingMovies van sujetas al plan de internet porlo que para
#este estudio pueden ser prescindibles, asÃ­ que las elimino y lo guardo en una nueva variable

datos.drop(['OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies'], axis=1, inplace=True)

In [74]:
datos

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,0002-ORFBO,True,Female,False,True,True,9,True,False,True,One year,True,Mailed check,65.60,593.30
1,0003-MKNFE,True,Male,False,True,True,9,True,True,True,Month-to-month,True,Mailed check,59.90,542.40
2,0004-TLHLJ,True,Male,False,True,True,4,True,False,True,Month-to-month,True,Electronic check,73.90,280.85
3,0011-IGKFF,True,Male,True,True,True,13,True,False,True,Month-to-month,True,Electronic check,98.00,1237.85
4,0013-EXCHZ,True,Female,True,True,True,3,True,False,True,Month-to-month,True,Mailed check,83.90,267.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,True,Female,False,True,True,13,True,False,True,One year,True,Mailed check,55.15,742.90
7263,9992-RRAMN,True,Male,False,True,True,22,True,True,True,Month-to-month,True,Electronic check,85.10,1873.70
7264,9992-UJOEL,True,Male,False,True,True,2,True,False,True,Month-to-month,True,Mailed check,50.30,92.75
7265,9993-LHIEB,True,Male,False,True,True,67,True,False,True,Two year,True,Mailed check,67.85,4627.65
7266,9995-HOTOH,True,Male,False,True,True,63,True,False,True,Two year,True,Electronic check,59.00,3707.60

In [75]:
#ahora voy a crear la columna de cuentas diarias utilizando la facturaciÃ³n
#mensual para calcular el valor diario

dias_mes = 30

datos['Cuentas_diarias'] = datos['Charges.Monthly'] / dias_mes

In [76]:
datos.tail()

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total,Cuentas_diarias
7262,9987-LUTYD,True,Female,False,True,True,13,True,False,True,One year,True,Mailed check,55.15,742.90,1.838333
7263,9992-RRAMN,True,Male,False,True,True,22,True,True,True,Month-to-month,True,Electronic check,85.10,1873.70,2.836667
7264,9992-UJOEL,True,Male,False,True,True,2,True,False,True,Month-to-month,True,Mailed check,50.30,92.75,1.676667
7265,9993-LHIEB,True,Male,False,True,True,67,True,False,True,Two year,True,Mailed check,67.85,4627.65,2.261667
7266,9995-HOTOH,True,Male,False,True,True,63,True,False,True,Two year,True,Electronic check,59.00,3707.60,1.966667

In [77]:
#primero crearÃ© una lista con las columnas booleanas a transformar en int
colum_2int = [
    'Churn',
    'SeniorCitizen',
    'Partner',
    'Dependents',
    'PhoneService',
    'MultipleLines',
    'InternetService',
    'PaperlessBilling'
]

In [78]:
#ahora voy a estandarizar los datos.
#los datos que tengo en booleano = True/False, los convertirÃ© en valores 1/0
# Convierto todas estas columnas (que ahora deberÃ­an ser 'bool') a tipo entero (int).
for col in colum_2int:
    # Verifico si la columna existe Y AHORA ES DE TIPO booleano antes de convertir a int
    if col in datos.columns and datos[col].dtype == bool:
        datos[col] = datos[col].astype(int)
    elif col in datos.columns:
         print(f"La columna '{col}' no es de tipo bool ({datos[col].dtype}). No se convirtiÃ³ a int.")
    else:
        print(f"La columna '{col}' no se encontrÃ³ en el DataFrame. Saltando conversiÃ³n a int.")

In [79]:
datos[colum_2int].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Churn             7267 non-null   int64
 1   SeniorCitizen     7267 non-null   int64
 2   Partner           7267 non-null   int64
 3   Dependents        7267 non-null   int64
 4   PhoneService      7267 non-null   int64
 5   MultipleLines     7267 non-null   int64
 6   InternetService   7267 non-null   int64
 7   PaperlessBilling  7267 non-null   int64
dtypes: int64(8)
memory usage: 454.3 KB

In [80]:
datos.head()

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total,Cuentas_diarias
0,0002-ORFBO,1,Female,0,1,1,9,1,0,1,One year,1,Mailed check,65.6,593.30,2.186667
1,0003-MKNFE,1,Male,0,1,1,9,1,1,1,Month-to-month,1,Mailed check,59.9,542.40,1.996667
2,0004-TLHLJ,1,Male,0,1,1,4,1,0,1,Month-to-month,1,Electronic check,73.9,280.85,2.463333
3,0011-IGKFF,1,Male,1,1,1,13,1,0,1,Month-to-month,1,Electronic check,98.0,1237.85,3.266667
4,0013-EXCHZ,1,Female,1,1,1,3,1,0,1,Month-to-month,1,Mailed check,83.9,267.40,2.796667

In [81]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7267 non-null   object
 1   Churn             7267 non-null   int64
 2   gender            7267 non-null   object
 3   SeniorCitizen     7267 non-null   int64
 4   Partner           7267 non-null   int64
 5   Dependents        7267 non-null   int64
 6   tenure            7267 non-null   int64
 7   PhoneService      7267 non-null   int64
 8   MultipleLines     7267 non-null   int64
 9   InternetService   7267 non-null   int64
 10  Contract          7267 non-null   object
 11  PaperlessBilling  7267 non-null   int64
 12  PaymentMethod     7267 non-null   object
 13  Charges.Monthly   7267 non-null   float64
 14  Charges.Total     7256 non-null   float64
 15  Cuentas_diarias   7267 non-null   float64
dtypes: float64(3), int64(9), object(4)
memory usage: 908.5+ KB

#ðŸ“Š Carga y anÃ¡lisis

In [82]:
#comienzo importando las bibliotecas que necesitarÃ©
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [83]:
#ahora voy a calcular la media
# Selecciono solo las columnas numÃ©ricas para calcular la media
# Excluyo la columna 'customerID' que es un identificador y no es numÃ©rica
numeric_cols = datos.select_dtypes(include=np.number).columns.tolist()
# Aseguro que 'customerID' no estÃ© en la lista de columnas numÃ©ricas si por alguna razÃ³n fue incluida
if 'customerID' in numeric_cols:
    numeric_cols.remove('customerID')

datos[numeric_cols].mean()

Churn                  1.000000
SeniorCitizen          0.162653
Partner                1.000000
Dependents             1.000000
tenure                32.346498
PhoneService           1.000000
MultipleLines          0.421770
InternetService        0.782441
PaperlessBilling       1.000000
Charges.Monthly       64.720098
Charges.Total       2280.634213
Cuentas_diarias        2.157337
dtype: float64

In [84]:
#voy a guardarlo en una variable y le quitarÃ© el index

data = datos[numeric_cols]

In [85]:
media = data.mean()

In [86]:
media

Churn                  1.000000
SeniorCitizen          0.162653
Partner                1.000000
Dependents             1.000000
tenure                32.346498
PhoneService           1.000000
MultipleLines          0.421770
InternetService        0.782441
PaperlessBilling       1.000000
Charges.Monthly       64.720098
Charges.Total       2280.634213
Cuentas_diarias        2.157337
dtype: float64

In [87]:
#ahora reviso la mediana
mediana = datos[numeric_cols].median()
mediana

Churn                  1.000000
SeniorCitizen          0.000000
Partner                1.000000
Dependents             1.000000
tenure                29.000000
PhoneService           1.000000
MultipleLines          0.000000
InternetService        1.000000
PaperlessBilling       1.000000
Charges.Monthly       70.300000
Charges.Total       1391.000000
Cuentas_diarias        2.343333
dtype: float64

In [88]:
#ahora la desviaciÃ³n estÃ¡ndar

desviacion = datos[numeric_cols].std()
desviacion

Churn                  0.000000
SeniorCitizen          0.369074
Partner                0.000000
Dependents             0.000000
tenure                24.571773
PhoneService           0.000000
MultipleLines          0.493876
InternetService        0.412614
PaperlessBilling       0.000000
Charges.Monthly       30.129572
Charges.Total       2268.632997
Cuentas_diarias        1.004319
dtype: float64

#ðŸ“„Informe final